### ISSUE TITLE
OAuth2 authentication init fails with ClassCastException

### ISSUE THREAD

**Issue by asoltesz** [spring-projects/spring-pulsar#500]
I am using Spring Pulsar with Spring Boot 3.2.0-M3 with the Pulsar Client 3.1.0.

I am configuring the OAuth2 (with JWT) like this (as the [docs says here](https://docs.spring.io/spring-pulsar/reference/reference/pulsar.html#client-authentication)):

~~~
spring:
    pulsar:
        client:
            authentication:
                plugin-class-name: org.apache.pulsar.client.impl.auth.oauth2.AuthenticationFactoryOAuth2
                param:
                    issuerUrl: https://idp.mycompany.com
                    privateKey: ...
~~~

I get the following error at application startup:

~~~
Caused by: java.lang.IllegalStateException: Unable to configure Pulsar authentication
...
Caused by: org.apache.pulsar.client.api.PulsarClientException$UnsupportedAuthenticationException: java.lang.ClassCastException: class org.apache.pulsar.client.impl.auth.oauth2.AuthenticationFactoryOAuth2 cannot be cast to class org.apache.pulsar.client.api.Authentication (org.apache.pulsar.client.impl.auth.oauth2.AuthenticationFactoryOAuth2 and org.apache.pulsar.client.api.Authentication are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @2b71fc7e)
	at org.apache.pulsar.client.impl.AuthenticationUtil.create(AuthenticationUtil.java:118) ~[pulsar-client-3.1.0.jar!/:3.1.0]
	at org.apache.pulsar.client.impl.PulsarClientImplementationBindingImpl.createAuthentication(PulsarClientImplementationBindingImpl.java:133) ~[pulsar-client-3.1.0.jar!/:3.1.0]
	at org.apache.pulsar.client.api.AuthenticationFactory.create(AuthenticationFactory.java:108) ~[pulsar-client-api-3.1.0.jar!/:3.1.0]
	... 85 common frames omitted
Caused by: java.lang.ClassCastException: class org.apache.pulsar.client.impl.auth.oauth2.AuthenticationFactoryOAuth2 cannot be cast to class org.apache.pulsar.client.api.Authentication (org.apache.pulsar.client.impl.auth.oauth2.AuthenticationFactoryOAuth2 and org.apache.pulsar.client.api.Authentication are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @2b71fc7e)
	at org.apache.pulsar.client.impl.AuthenticationUtil.create(AuthenticationUtil.java:111) ~[pulsar-client-3.1.0.jar!/:3.1.0]
	... 87 common frames omitted
~~~

Looks like the code assumes that the factory can be cast to the Authentication class which doesn't look like the class design at all.

**Comment by onobc** [comment]
Hi @asoltesz ,
Looks like you found a bug in the docs. Can you try `org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2` instead?

**Comment by asoltesz** [comment]
With AuthenticationOAuth2, I get a different exception:

~~~
Caused by: org.apache.pulsar.client.api.PulsarClientException$UnsupportedAuthenticationException: org.apache.pulsar.shade.org.apache.commons.lang.NotImplementedException: Deprecated; use EncodedAuthenticationParameterSupport
	at org.apache.pulsar.client.impl.AuthenticationUtil.create(AuthenticationUtil.java:118) ~[pulsar-client-3.1.0.jar:3.1.0]
	at org.apache.pulsar.client.impl.PulsarClientImplementationBindingImpl.createAuthentication(PulsarClientImplementationBindingImpl.java:133) ~[pulsar-client-3.1.0.jar:3.1.0]
	at org.apache.pulsar.client.api.AuthenticationFactory.create(AuthenticationFactory.java:108) ~[pulsar-client-api-3.1.0.jar:3.1.0]
	... 82 common frames omitted
Caused by: org.apache.pulsar.shade.org.apache.commons.lang.NotImplementedException: Deprecated; use EncodedAuthenticationParameterSupport
	at org.apache.pulsar.client.impl.auth.oauth2.AuthenticationOAuth2.configure(AuthenticationOAuth2.java:91) ~[pulsar-client-3.1.0.jar:3.1.0]
	at org.apache.pulsar.client.impl.AuthenticationUtil.create(AuthenticationUtil.java:112) ~[pulsar-client-3.1.0.jar:3.1.0]
	... 84 common frames omitted
~~~

It looks like this AuthenticationOAuth2 doesn't support initializing with the "param" section (map of parameters).

**Comment by onobc** [comment]
Thanks @asoltesz - sorry you are running into this and we will take a look in the next 24-48 hrs. In the meantime, a workaround may be to 

> If you need more control over the configuration, consider registering one or more PulsarClientBuilderCustomizer beans.

**Comment by onobc** [comment]
PR in Boot - hopefully we can get it squeezed in for the `3.2.1` release next week. 🤞🏻

**Comment by onobc** [comment]
Closed via https://github.com/spring-projects/spring-boot/commit/3d42dc7c6dfb5b8dae3574876f930d1b588e03e8
